longhorn/dep-versions

- versions.json
https://github.com/longhorn/longhorn/issues/10208
> chore: add versions.json

- versions.json
> chore: update go-spdk-helper commit

- scripts/build-go-spdk-helper.sh
- scripts/build-libjsonc.sh
- scripts/build-liblonghorn.sh
- scripts/build-nvme-cli.sh
- scripts/build-spdk.sh
- scripts/build-tgt.sh
> feat: add build scripts for dependencies

- scripts/common.sh
> feat: add common.sh for shared functions

- .github/workflows/update-dep-versions-in-longhorn-repo.yml
The workflow will create a longhorn/longhorn PR to update the versions of CSI sidecard images and support-bundle-kit in chart/values.yaml, chart/questions.yaml, chart/README.md and deployment manifests based on versions.json.
Longhorn/longhorn#10600
> feat(workflow): add update-dep-versions-in-longhorn-repo.yml

- .github/workflows/update-dep-versions-in-longhorn-repo.yml
> chore(workflow): update PR title in update-dep-versions-in-longhorn-repo.yml

- versions.json
Longhorn/longhorn#10313
Signed-off-by: Derek Su <derek.su@suse.com>
> feat: bump spdk to 0c70269 (v24.09.0+2)

- .github/workflows/trigger-builds.yaml
- scripts/build-spdk.sh
> chore(workflow): trigger downstream image build workflow if PR is opened or pushed

- scripts/build-spdk.sh
> feat: implement ublk frontend for v2 data engine

- versions.json
> chore(cve): update components version

- scripts/build-spdk.sh
> fix: target armv8 for backword compatibility

- .github/workflows/update-dep-versions-in-longhorn-repo.yml
> fix(workflow): typo

- scripts/build-spdk.sh
See more details https://github.com/longhorn/longhorn/issues/10768#issuecomment-2825685800
longhorn/longhorn#10768
> fix: specify gcc13 for SPDK building

- versions.json
Ref: https://github.com/linux-nvme/nvme-cli/blob/v2.10.2/subprojects/libnvme.wrap
Signed-off-by: Derek Su <derek.su@suse.com>
> chore: add libnvme

- versions.json
> feat: update spdk and go-spdk-helper tags in versions.json

- versions.json
> chore(cve): update support-bundle-kit to v0.0.55

- versions.json
> chore: update support-bundle-kit to v0.0.57

- scripts/build-go-spdk-helper.sh
- scripts/build-libjsonc.sh
- scripts/build-liblonghorn.sh
- scripts/build-libqcow.sh
- scripts/build-nfs-ganesha.sh
- scripts/build-nvme-cli.sh
- scripts/build-spdk.sh
- scripts/build-tgt.sh
- versions.json
> feat: add libqcow

- versions.json
> fix: invalid livenessprobe tag

- .github/workflows/create-dep-versions-update-pr-in-longhorn-repo.yml
- .github/workflows/trigger-builds.yaml
> chore(workflow): replace PAT with longhorn-github-bot APP Token

- versions.json
> chore: update support-bundle-kit to v0.0.62

- versions.json
> chore: update versions.json

- versions.json
> chore: update support-bundle-kit to v0.0.64
